server:
  port: ${port:8888}

spring:
  application:
    name: config-server-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config # not needed, this is already the default
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/