spring:
  application:
    name: todo-service
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        service-id: config-server-service

eureka:
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false