spring:
  application:
    name: todo-event-listener-service
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        service-id: config-server-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/